# Generated by Django 4.2.15 on 2024-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('to read', 'To Read'), ('on going', 'ON Going'), ('completed', 'Completed')], default='to read', max_length=255),
        ),
    ]
