# Generated by Django 4.2.15 on 2024-08-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksummary',
            name='summary_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
